const mongoose = require('mongoose');

const DonorSchema = new mongoose.Schema({
    // uniqueID is auto-generated by MongoDB as _id
    name: { type: String, required: true },
    mobile_no: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    blood_type: { type: String, required: true },
    dob: { type: Date, required: true },
    gender: { type: String, required: true },
    location: {
        lat: { type: Number, required: true },
        lng: { type: Number, required: true }
    },
    reportCount: { type: Number, default: 0 }
});

module.exports = mongoose.model('Donor', DonorSchema);